# Generated by Django 4.2.3 on 2023-07-11 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fleet_number', models.CharField(max_length=255)),
                ('plate_number', models.CharField(max_length=255)),
                ('trailer_type', models.CharField(max_length=255)),
                ('capacity', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('chasis_number', models.CharField(max_length=255)),
                ('remarks', models.TextField(blank=True, max_length=255, null=True)),
                ('trailer_model', models.CharField(max_length=255)),
                ('condition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.condition')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.driver')),
            ],
        ),
    ]
