# Generated by Django 4.2.3 on 2023-07-13 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_aafleetno_abtruck_batrip_bbmtrl_cafo_ebadvance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drvleave',
            old_name='addressDuringLeave',
            new_name='AddressDuringLeave',
        ),
        migrations.RenameField(
            model_name='drvleave',
            old_name='DrvId',
            new_name='driverID',
        ),
        migrations.RenameField(
            model_name='drvleave',
            old_name='leaveType',
            new_name='drvLeaveType',
        ),
        migrations.RenameField(
            model_name='drvleave',
            old_name='UserId',
            new_name='fkUserId',
        ),
        migrations.RemoveField(
            model_name='drvleave',
            name='firstWorkDate',
        ),
        migrations.RemoveField(
            model_name='drvleave',
            name='lastWorkDate',
        ),
        migrations.RemoveField(
            model_name='drvleave',
            name='leaveDays',
        ),
        migrations.RemoveField(
            model_name='drvleave',
            name='leaveEndingDate',
        ),
        migrations.RemoveField(
            model_name='drvleave',
            name='leaveFilledDate',
        ),
        migrations.RemoveField(
            model_name='drvleave',
            name='leaveStartingDate',
        ),
        migrations.AddField(
            model_name='drvleave',
            name='drvLeaveEndDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drvleave',
            name='drvLeaveStartDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drvemergecycontact',
            name='driverID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.driver'),
        ),
        migrations.AlterField(
            model_name='drvlicence',
            name='driverID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.driver'),
        ),
        migrations.AddField(
            model_name='drvleave',
            name='FirstWorkDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drvleave',
            name='LastworkDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drvleave',
            name='leavedays',
            field=models.CharField(default=12, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drvleave',
            name='leavefilledDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
