# Generated by Django 4.2.3 on 2023-08-01 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_addressduringleave_drvleave_addressduringleave_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafo',
            name='ShipmentCode',
            field=models.CharField(default=123, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='cmrName',
            field=models.CharField(default=123, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='abtruck',
            name='DrvId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.driver'),
        ),
        migrations.AlterField(
            model_name='cafo',
            name='foAdvanceLock',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cafo',
            name='foFuelLock',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cafo',
            name='foPerdiumLock',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dafuel',
            name='FoId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.cafo'),
        ),
    ]
