# Generated by Django 4.2.3 on 2023-08-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_cafo_shipmentcode_customer_cmrname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafo',
            name='foNo',
            field=models.CharField(max_length=25),
        ),
    ]
