# Generated by Django 4.2.3 on 2023-08-01 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_cafo_fono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drvlicence',
            name='driverID',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='licence', to='api.driver'),
        ),
        migrations.AlterField(
            model_name='drvpassport',
            name='DrvId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='passport', to='api.driver'),
        ),
    ]
