# Generated by Django 4.2.3 on 2023-08-18 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_useractivity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivity',
            name='model',
        ),
    ]
