# Generated by Django 4.2.3 on 2023-08-20 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_useractivity_model_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useractivity',
            old_name='action',
            new_name='activity_type',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='model_name',
        ),
        migrations.AddField(
            model_name='useractivity',
            name='method',
            field=models.CharField(default=12, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useractivity',
            name='url',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
