# Generated by Django 4.2.3 on 2023-08-20 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_useractivity_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserActivity',
        ),
    ]
