# Generated by Django 4.2.3 on 2023-08-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_delete_useractivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
