# Generated by Django 4.2.3 on 2023-08-21 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_rename_userid_aafleetno_fkuserid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MtrCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mtrCatCol', models.CharField(max_length=255)),
                ('UserId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
