# Generated by Django 4.2.3 on 2023-08-23 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_mtrcat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bbmtrl',
            name='mtrCat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mtrcat'),
        ),
    ]
