# Generated by Django 4.2.3 on 2023-08-23 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_bbmtrl_mtrcat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bbmtrl',
            name='mtrCat',
            field=models.CharField(max_length=255),
        ),
    ]
