# Generated by Django 4.2.3 on 2023-08-23 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_bbmtrl_mtrcat'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfractionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infractionType', models.CharField(max_length=255)),
                ('fkUserId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Infraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infractionDate', models.DateField()),
                ('infractionLocation', models.CharField(max_length=255)),
                ('infractionRemark', models.TextField()),
                ('drvId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.driver')),
                ('fkUserId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('infractionType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.infractiontype')),
            ],
        ),
    ]
